"""Compatibility facade for the weather reliability report API."""

from __future__ import annotations

from .reliability.config import (
    DISCORD_GREEN,
    DISCORD_RED,
    DISCORD_YELLOW,
    GLOBAL_SCHEDULE_ENV,
    IDENTIFIER_PATTERN,
    KMA_BASE_INTERVAL_HOURS,
    KST,
    LOGGER,
    MANIFEST_TABLE,
    SCHEDULE_ENV,
    WEATHER_BRONZE_DAG_ID,
    WEATHER_TABLE,
    WEBHOOK_ENVS,
    WeatherReportConfig,
    ask_seoul_schema,
    discord_webhook_url,
    is_dev_target,
    report_config,
    report_dag_schedule,
    sql_identifier,
    trino_catalog,
)
from .reliability.discord import (
    _discord_payload,
    _format_bool,
    _format_minutes,
    _icon,
    _status_icon,
    _status_label,
    format_weather_discord_message,
    send_discord_message,
)
from .reliability.report import build_weather_reliability_report
from .reliability.trino_repository import (
    _age_minutes,
    _fetch_one,
    _qualified,
    _sql_string,
    _sql_timestamp_utc,
    _weather_cutoffs,
    collect_dag_run_summary,
    collect_weather_summary,
    freshness_status,
    trino_cursor,
)


__all__ = [
    "_age_minutes",
    "_discord_payload",
    "_fetch_one",
    "_format_bool",
    "_format_minutes",
    "_icon",
    "_qualified",
    "_sql_string",
    "_sql_timestamp_utc",
    "_status_icon",
    "_status_label",
    "_weather_cutoffs",
    "DISCORD_GREEN",
    "DISCORD_RED",
    "DISCORD_YELLOW",
    "GLOBAL_SCHEDULE_ENV",
    "IDENTIFIER_PATTERN",
    "KMA_BASE_INTERVAL_HOURS",
    "KST",
    "LOGGER",
    "MANIFEST_TABLE",
    "SCHEDULE_ENV",
    "WEATHER_BRONZE_DAG_ID",
    "WEATHER_TABLE",
    "WEBHOOK_ENVS",
    "WeatherReportConfig",
    "ask_seoul_schema",
    "build_weather_reliability_report",
    "collect_dag_run_summary",
    "collect_weather_summary",
    "discord_webhook_url",
    "format_weather_discord_message",
    "freshness_status",
    "is_dev_target",
    "report_config",
    "report_dag_schedule",
    "send_discord_message",
    "sql_identifier",
    "trino_catalog",
    "trino_cursor",
]
